### ISSUE TITLE
Improve UI with uploading a photo

### ISSUE THREAD

**Issue by dmichelin** [sotch-pr35mac/snapstone#17]
On the word detail page, 4 changes need to be made:

1. Prevent navigation away from the page when it's uploading
2. While it's uploading, display some cute animation below the photo
3.  After uploading, hide the animation then display the text and confidence at the bottom of the screen
4. Have a nonfunctional button that is a star or something that the user can click to eventually bookmark it

The trigger for when the photo has been uploaded is the logResponse(e) function on line 113 of word-detail-page.js.

**Comment by sotch-pr35mac** [comment]
The data coming back from the server will ideally be in the following format: 
```
[
   {
      traditional: 'String',
      simplified: 'String',
      pinyin: 'String',
      definitions: [ 'String', 'String', 'String']
   }
]
```

That is to say that the response will be an array of objects with the fields, traditional (of type string), simplified (of type string), pinyin (of type string), and definitions (which is an array of strings).  We should be able to display all that information to the user. 

What comes back from the server will really be a wild card, so we should be able to handle the events of not having any result come back at all (ie there was no text in the picture) and having a lot of word objects. 

When the add to bookmarks button is pressed, it should get the individual word object described above for the given word (all the fields: traditional, simplified, pinyin, and definitions). A request to the server for adding a word to the bookmarks can be found in the `develop` branch at the file [`/app/home/home-page.js`](https://github.com/sotch-pr35mac/snapstone/blob/develop/app/home/home-page.js) at the function `addBookmark()` currently on line 196. 

If you have any questions let me know!
